# Generated by Django 4.0 on 2025-09-05 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('speed_signer', 'Speed Signer'), ('perfect_week', 'Perfect Week'), ('conversation_master', 'Conversation Master'), ('streak_master', 'Streak Master'), ('daily_champion', 'Daily Champion')], max_length=20)),
                ('description', models.TextField()),
                ('requirement', models.JSONField()),
                ('xp_reward', models.IntegerField(default=100)),
                ('icon', models.CharField(default='🏆', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('animals', 'Sign 5 Animals'), ('colors', 'Sign 5 Colors'), ('numbers', 'Sign Numbers 1-10'), ('family', 'Sign Family Members'), ('food', 'Sign 5 Foods')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_signs', models.JSONField()),
                ('xp_reward', models.IntegerField(default=200)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('letters', 'Letters'), ('words', 'Words'), ('phrases', 'Phrases'), ('conversations', 'Conversations')], max_length=20)),
                ('required_level', models.IntegerField(default=1)),
                ('xp_reward', models.IntegerField(default=50)),
                ('content', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('sign_race', 'Sign Race'), ('memory_match', 'Memory Match'), ('story_mode', 'Story Mode'), ('daily_challenge', 'Daily Challenge')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('time_taken', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('skill_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.skilltree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'unique_together': {('user', 'skill_tree')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=10)),
                ('total_xp', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'unique_together': {('user', 'period')},
            },
        ),
    ]
